name: Deploy Test

on:
  workflow_dispatch:   # 수동 실행

jobs:
  ssh-test:
    runs-on: ubuntu-latest

    steps:
      - name: SSH to EC2 (Test)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "✅ SSH connection successful"
            hostname
            docker --version
